;MAINMULT.ASM
.MODEL SMALL
.STACK 100H
.DATA 

MSG_INTRO DB 'ILLUSTRATION OF MULTPLICATION AND DIVISON $'
MSG_MUL DB 'USING MUL AND BYTE FORM MULTIPLIER = AL$'
MSG_IMUL DB 'USING IMUL AND WORD FORM MULTIPLIER = AX$'
MSG_DIV DB 'USING DIV AND BYTE FORM DIVIDEND=AX QUOTIENT=AL$'
MSG_DIV1 DB 'USING DIV AND BYTE FORM DIVIDEND=AX REMINDER=AH$'
MSG_DIV2 DB 'USING DIV AND WORD FORM DIVIDEND=DX:AX QUOTIENT=AX$'
MSG_DIV3 DB 'USING DIV AND BYTE FORM DIVIDEND=DX:AX REMINDER=DX$'
MSG_IDIV DB 'USING IDIV $'
NEWLINE DB 0AH,0DH,'$'


.CODE
MAIN PROC
    MOV AX,2
    MOV BX,3 
    
    
    
    MUL BX    
    
    MOV DX,AX
    ADD DX,30H
    MOV AH,2
    INT 21H
    
    MOV AX,@DATA
    MOV DS,AX
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H 
    
    LEA DX ,MSG_MUL  ;PRINTING MUL MSG
    MOV AH,9
    INT 21H  
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H
    
    MOV AL,2
    MOV BX,3
    
    IMUL BX
    
    MOV DX,AX
    ADD DX,30H
    MOV AH,2
    INT 21H
    
    MOV AX,@DATA
    MOV DS,AX
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H 
    
    LEA DX ,MSG_IMUL  ;PRINTING IMUL MSG
    MOV AH,9
    INT 21H
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H   
    
    MOV AX,7
    MOV BL,3
    
    DIV BL
    
    MOV DL,AH
    ADD DL,30H
    MOV AH,2
    INT 21H 
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H 
    
    LEA DX ,MSG_DIV1  ;PRINTING REMINDER MSG
    MOV AH,9
    INT 21H
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H 
    
    MOV AX,7
    MOV BL,3
    
    DIV BL
    
    
    MOV DL,AL
    ADD DL,30H
    MOV AH,2
    INT 21H 
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H 
    
    LEA DX ,MSG_DIV  ;PRINTING QUTOIENT MSG
    MOV AH,9
    INT 21H
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H
    
    MOV DX,0
    MOV AX,7
    MOV BX,3 ; NOW DX:AX CONTAINS 4
    
    DIV BX
    
    
    MOV DX,AX
    ADD DX,30H
    MOV AH,2
    INT 21H 
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H 
    
    LEA DX ,MSG_DIV2  ;PRINTING QUTOIENT MSG
    MOV AH,9
    INT 21H
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H
    
    MOV DX,0
    MOV AX,7
    MOV BX,3 ; NOW DX:AX CONTAINS 4
    
    DIV BX
    
    
    ADD DX,30H
    MOV AH,2
    INT 21H 
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H 
    
    LEA DX ,MSG_DIV3  ;PRINTING REMINDER MSG
    MOV AH,9
    INT 21H
    
    LEA DX ,NEWLINE  ;PRINTING NEWLINE
    MOV AH,9
    INT 21H
     
    
   
    MAIN ENDP
    END MAIN